### PR TITLE
added support for a esp32 model

### PR DESCRIPTION
**Pull request by scottrcarlson**
Support for ESP32 based model. Called it B1 (arbitrarily)
I also removed what appears to be duplicate code.

### CODE REVIEW

**Comment by markqvist** [comment]
Hi Scott
Sorry for never getting back to this. Some pretty severe stuff happened 2 days after you submitted this pull request, so it was lost in the general stream of life events. Since a lot of the code was changed since then, I can't merge it now.

Any change you could link me some info to the ESP32 model you were talking about?

**Comment by scottrcarlson** [comment]
Hi Mark --

No problem, sorry to hear, hope all is well.

I actually started to re-arrange the control flow a bit (non-blocking main
loop for one example) as I was having some esp32 related crashing issues.
Its been a while since I've revisited it. As soon as I do I will prepare
another PR. I did have it fully functioning with Reticulum though!

Just want to say, I am enamored with the Reticulum project. I stumbled onto
it last year and was able to get the system up and running with a couple of
my esp32 units. The approach you're taking is brilliant.

I've developed several variations of simpler comms networks utilizing LoRa.
A few years back I did demo at DEF CON. My units were all standalone (RPi
or ESP32 based). I was actually going back into design mode when I saw your
project. You certainly covered all of the important bases! I've read your
documentation several times and am overdue to go over them again.

I will circle around on this soon I hope, I am very much looking forward to
spinning up your system again, I see you've been working on it.

Best Regards,
Scott

**Comment by markqvist** [comment]
Thanks, it's all good now.

The current version of the RNode firmware now has nonblocking IO and much better queuing as well, although it's not as elegantly implemented as I'd like. I initially used Arduino for the firmware to make it easier for people to hack their own versions, but I think I will move it away from the Arduino environment in the near future, since it's preventing me from implementing it as I'd like. I'll of course leave the Arduino version there for people to hack on.

Ah, very cool! I tried searching for the talk, is there a video of it anywhere?

Yes, a lot has happened with Reticulum in the last months, and it's nearing an API stable alpha release. I'm probably going to add DTN support on both raw packets, links and resource transfers first though. Unfortunately the documentation is not quite up to date with the current implementation, so if there's anything you're interested in, just ask me :)

Let me know if you get the ESP32 model up and running. I'd be happy to add support for other models, it just requires a little coordination with the model numbers and such.

Cheers,
Mark

**Comment by scottrcarlson** [comment]
Greetings Mark --

It was a DEF CON 24 Demolabs presentation. It was not a talk/presentation
per-say. More of a hands on demo, with small groups of people for a few
hours. Every year for the past 4 years or so, I've brought various
prototypes for fun. Attached are some photos over the years of the
standalone comms units. I built a version that also pairs to android app
via ble, but for obvious reasons, I couldn't in good faith deploy that
version at a security conference.

I've attached a few photos of previous unit designs. All of them were
utilizing a readonly FS on raspberry pi zero's. I've recently (as our
conversation started) been using esp32 based platform to experiment as well
which is the photo with the TTGO hardware in it.

I'm long over-due to bring my various software repo's from private to
public status.

I'm excited to work with (and maybe help out!) Reticulum, I really believe
you've got the proper path forward from a technical perspective! Reading
through your documentation I keep saying "holy shit, this is obviously the
right way of going about this!".

Maybe sometime I will run your ear off about my various takes on "routing".
Some more elaborate than others. All fun though!

*** Having size limit issues attaching photos. I'll try to send in multiple
emails.

Best Regards,
Scott

**Comment by scottrcarlson** [comment]
Mark --

Tried sending some attached photos, but I think the limits are small
funneling through github.

Scott

**Comment by markqvist** [comment]
Ah, very cool. Would have loved to see the photos, but unfortunately they did not go through. If you find the time, you can try sending them directly to my email. Thanks for the words of encouragement! There's still a long way to go, and a lot of work in the pipeline for Reticulum, but I also feel that it is starting to get usable in the sense I envisioned when I started the project.

Your help would be much appreciated, whether that be code contributions, or using the protocol and reporting back what you find.

I'm really overdue for updating the Reticulum documentation though. While all the core ideas are still valid, a lot of things have been fleshed out and improved in the actual implementation, and I guess it's kind of a prerequisite that people can actually understand what's going on under the hood ;)

**Pull request closed without merging**
