### PR TITLE
Change for using device by-id

### PR DESCRIPTION
**Pull request by SebastianObi**
Hi Mark,

first thanks for your great reticulum project :)

I have made some small changes to allow using serial device by-id.
rnodeconf.py /dev/serial/by-id/usb-1a86_USB_Single_Serial_537D019596-if00 --autoinstall

This is helpful to select the devices uniquely.
Maybe you can add this or improve my modification.

Kind regards
Sebastian

### CODE REVIEW

**Comment by markqvist** [comment]
Hi @SebastianObi 
Thanks for this addition! I will merge and include this in the next release of rnodeconf.

**Comment by markqvist** [comment]
Btw, did you test that it still works using the port selection menu?

**Comment by SebastianObi** [comment]
Good to remember me. No I didn't test it. I test it later when I'm home.

**Comment by SebastianObi** [comment]
I tested it. Everything looks good also with the port selection menu.

**Comment by markqvist** [comment]
Thanks! Merged.

**Pull request merged**
